# Generated by Django 5.0.7 on 2024-10-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_registroingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
